FROM 1587/osc-builder:stage1
#安装交叉编译环境
RUN dpkg --add-architecture armel \
    && dpkg --add-architecture arm64 \
    && dpkg --add-architecture powerpc \
    && wget http://emdebian.org/tools/debian/emdebian-toolchain-archive.key \
    && gpg --import /emdebian-toolchain-archive.key \
    && apt-key add /emdebian-toolchain-archive.key \
    && rm /emdebian-toolchain-archive.key \
    && echo "deb http://emdebian.org/tools/debian jessie main extra" >> ${SOURCES_LIST} \
    && echo "deb-src http://emdebian.org/tools/debian jessie main extra" >> ${SOURCES_LIST} \
    && apt-get update \
    && apt-get install -y --force-yes --no-install-recommends \
            linux-libc-dev:armel libc6-dev:armel libcap-dev:armel libmount-dev:armel libdbus-1-dev:armel \
            libgcc-4.9-dev:armel libgcc-4.9-dev:armel libstdc++-4.9-dev:armel \
            linux-libc-dev:powerpc libc6-dev:powerpc libcap-dev:powerpc libmount-dev:powerpc \
            libdbus-1-dev:powerpc libgcc-4.9-dev:powerpc libstdc++-4.9-dev:powerpc \
            linux-libc-dev:arm64 libc6-dev:arm64 libcap-dev:arm64 libmount-dev:arm64 libdbus-1-dev:arm64 \
            libgcc-4.9-dev:arm64 libgcc-4.9-dev:arm64 libstdc++-4.9-dev:arm64 \
            crossbuild-essential-armel crossbuild-essential-arm64  crossbuild-essential-powerpc \
    && apt-get -y --force-yes --no-install-recommends autoremove \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists
